### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by Franklin005** [AlirezaSalehy/WAVRecorder#1]
Which Hardware did you use besides the microphone and the arduino due? How is the hardware connected/ How is the setup?
Can you share a schematic or a picture of the hardware construction?
Thanks in advance

**Comment by Alireza99Salehi** [comment]
Hi, friend thanks for your interest. Sorry for lack of documents i was in holiday somehow and did not have enough time to add explanation. i try to add answer to all the questions as soon as possible.

**Comment by Alireza99Salehi** [comment]
> Which Hardware did you use besides the microphone and the arduino due? How is the hardware connected/ How is the setup?
> Can you share a schematic or a picture of the hardware construction?
> Thanks in advance

I'v added some explanation recently. Check and tell me if there is some more things to explain; So i can add them, too.
