### ISSUE TITLE
Library not Valid

### ISSUE THREAD

**Issue by Geethukulal** [AlirezaSalehy/WAVRecorder#3]
I cannot add this zip file to my arduino ide this error comes in the monitor
Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: library not valid

**Comment by Alireza99Salehi** [comment]
Hi, thanks for reaching out. Basically, it's not structured in Arduino library format. But there are some ways to use the code. If you look inside `library` folder which resides at the root of repository, you'll see `library.ino` file and a `src` subfolder.  The `library.ino` could be replaced by your entry code.  And `src` subfolder is where you put other dependencies and utilities.

Hope this helps!
A. R. Salehy
