### ISSUE TITLE
Zip file is not adding to Arduino ide 

### ISSUE THREAD

**Issue by Abhishekbirwaz** [AlirezaSalehy/WAVRecorder#4]
When I add zip file to Arduino ide library It's showing error like 
error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: library not valid
Please give me solution

**Comment by Alireza99Salehi** [comment]
Hi! Thanks for feed back.
It is duplicated, please refer to [#3 ](https://github.com/A-R-S-D/WAVRecorder/issues/3).
