### ISSUE TITLE
hwo is the output played?

### ISSUE THREAD

**Issue by rickyelqasem** [AlirezaSalehy/WAVRecorder#7]
In your example circuit I don't see an output/pin.

how is the audio played on a speaker and here is the setup of the output pin?

thx

**Comment by Alireza99Salehi** [comment]
The demo example provides an explanation for audio recording and storing it somewhere like a SD card.  How ever playing the recorded .WAV file on SD card is as simple as playing any other audio file using open-source libraries like [ESP8266Audio](https://github.com/earlephilhower/ESP8266Audio). 

Any way this library also uses ESP8266Audio for playing audio. The following lines of code offers you needed information in this regard.
https://github.com/AlirezaSalehy/WAVRecorder/blob/04a882ef3dfe92594650ac0e2998066a53539aff/library/src/AudioSystem.cpp#L10 https://github.com/AlirezaSalehy/WAVRecorder/blob/04a882ef3dfe92594650ac0e2998066a53539aff/library/src/AudioSystem.h#L19 However this is a very limited usage of ESP8266Audio library only to test the process of recording. So please refer to that lib for more extensive usage. 

Regards 
A.R.S.D

**Comment by Alireza99Salehi** [comment]
Please let me know if that helped and to close the issue.
