### ISSUE TITLE
reboot all again at esp32

### ISSUE THREAD

**Issue by JasonYANG170** [AlirezaSalehy/WAVRecorder#8]
Core  0 register dump:
MEPC    : 0x4038522a  RA      : 0x4038691e  SP      : 0x3fc8dd40  GP      : 0x3fc8bc00  
TP      : 0x3fc74f50  T0      : 0x7fffffff  T1      : 0x420095f8  T2      : 0x00000002  
S0/FP   : 0xffffffff  S1      : 0x00000000  A0      : 0x3fc9624c  A1      : 0x3fc95a74  
A2      : 0x00000018  A3      : 0x3fc95a74  A4      : 0x00000018  A5      : 0x3fc95a74  
A6      : 0xfa000000  A7      : 0x00000003  S2      : 0xffffffff  S3      : 0x3fc9624c  
S4      : 0x00000004  S5      : 0x00000000  S6      : 0x00000000  S7      : 0x3c040276  
S8      : 0x00000000  S9      : 0x00000002  S10     : 0x00000001  S11     : 0x00000000  
T3      : 0x3fc8eaa8  T4      : 0x00000000  T5      : 0x00000001  T6      : 0xfffc0000  
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000018  MTVAL   : 0xfec77de3  
MHARTID : 0x00000000  

Stack memory:
3fc8dd40: 0x3fc8de20 0x3c059ac0 0x3fc8dd78 0x3fc9624c 0xffffffff 0x00000000 0x3fc96228 0x40385da0
3fc8dd60: 0x00000001 0xffffffff 0x00000001 0xffffffff 0x00000000 0x00000000 0x00000000 0x0000031e
3fc8dd80: 0x00000000 0x00000000 0x00000002 0x3fc8e9a8 0x00000002 0x00000000 0x3fc8e9a8 0x42011c48
3fc8dda0: 0x00000001 0x60040000 0x00000000 0xffffffff 0x0000000e 0x0000000a 0x00000003 0x3fc97cc4
3fc8ddc0: 0x00048c00 0x3fc8f000 0x00000000 0x3fc8f000 0x00000001 0x3c040274 0x3fc8b58c 0x4200c0b2
3fc8dde0: 0x00048c00 0x3fc8f000 0x00000000 0x00000004 0x3fc8de30 0x3fc8d1d4 0x00000004 0x42009606
3fc8de00: 0x3fc8de20 0x3fc8e958 0x3fc8de70 0x42009d18 0x3fc8de30 0x3fc8f000 0x3fc8de70 0x42000b18
3fc8de20: 0x00000074 0x3fc8eabc 0x00000000 0x4038661a 0x00000000 0x0000000a 0x00000003 0xe155b0fe
3fc8de40: 0x00048c00 0x00000246 0x00000003 0x3fc97cc4 0x00048c00 0x000000fa 0x00000000 0x00000000
3fc8de60: 0x003fffff 0x00000024 0x3fca943c 0x40380262 0x00000000 0x00000000 0x00000000 0x40380408
3fc8de80: 0x00001881 0x00000246 0x00000005 0x00000001 0x00001881 0x8000000a 0x3fc8e968 0x403801ee
3fc8dea0: 0x00000001 0x3fc8dea8 0xffffffff 0x3fc93288 0x3fc93288 0x00000000 0x3fc8debc 0xffffffff
3fc8dec0: 0x3fc8debc 0x3fc8debc 0x00000000 0x3fc8ded0 0xffffffff 0x3fc8ded0 0x3fc8ded0 0x00000000
3fc8dee0: 0x3fc8dee4 0xffffffff 0x3fc8dee4 0x3fc8dee4 0x00000000 0x3fc8def8 0xffffffff 0x3fc8def8
3fc8df00: 0x3fc8def8 0x00000000 0x3fc8df0c 0xffffffff 0x3fc8df0c 0x3fc8df0c 0x00000000 0x3fc8df20
3fc8df20: 0xffffffff 0x3fc8df20 0x3fc8df20 0x00000000 0x3fc8df34 0xffffffff 0x3fc8df34 0x3fc8df34
3fc8df40: 0x00000000 0x3fc8df48 0xffffffff 0x3fc8df48 0x3fc8df48 0x00000000 0x3fc8df5c 0xffffffff
3fc8df60: 0x3fc8df5c 0x3fc8df5c 0x00000000 0x3fc8df70 0xffffffff 0x3fc8df70 0x3fc8df70 0x00000000
3fc8df80: 0x3fc8df84 0xffffffff 0x3fc8df84 0x3fc8df84 0x00000000 0x3fc8df98 0xffffffff 0x3fc8df98
3fc8dfa0: 0x3fc8df98 0x00000000 0x3fc8dfac 0xffffffff 0x3fc8dfac 0x3fc8dfac 0x00000000 0x3fc8dfc0
3fc8dfc0: 0xffffffff 0x3fc8dfc0 0x3fc8dfc0 0x00000000 0x3fc8dfd4 0xffffffff 0x3fc8dfd4 0x3fc8dfd4
3fc8dfe0: 0x00000000 0x3fc8dfe8 0xffffffff 0x3fc8dfe8 0x3fc8dfe8 0x00000000 0x3fc8dffc 0xffffffff
3fc8e000: 0x3fc8dffc 0x3fc8dffc 0x00000000 0x3fc8e010 0xffffffff 0x3fc8e010 0x3fc8e010 0x00000000
3fc8e020: 0x3fc8e024 0xffffffff 0x3fc8e024 0x3fc8e024 0x00000000 0x3fc8e038 0xffffffff 0x3fc8e038
3fc8e040: 0x3fc8e038 0x00000000 0x3fc8e04c 0xffffffff 0x3fc8e04c 0x3fc8e04c 0x00000000 0x3fc8e060
3fc8e060: 0xffffffff 0x3fc8e060 0x3fc8e060 0x00000000 0x3fc8e074 0xffffffff 0x3fc8e074 0x3fc8e074
3fc8e080: 0x00000000 0x3fc8e088 0xffffffff 0x3fc8e088 0x3fc8e088 0x00000000 0x3fc8e09c 0xffffffff
3fc8e0a0: 0x3fc8e09c 0x3fc8e09c 0x00000000 0x3fc8e0b0 0xffffffff 0x3fc8e0b0 0x3fc8e0b0 0x00000000
3fc8e0c0: 0x3fc8e0c4 0xffffffff 0x3fc8e0c4 0x3fc8e0c4 0x00000002 0x3fc8e0d8 0xffffffff 0x3fc911ac
3fc8e0e0: 0x3fc95a60 0x00000001 0x3fc8e0ec 0xffffffff 0x3fc92814 0x3fc92814 0x00000000 0x3fc8e0f8
3fc8e100: 0x00000000 0x00000000 0x00000000 0x3fc8e110 0xffffffff 0x3fc8e110 0x3fc8e110 0x00000000
3fc8e120: 0x3fc8e124 0xffffffff 0x3fc8e124 0x3fc8e124 0x00000001 0x00000001 0x00000000 0x0001ffff

ELF file SHA256: 319c20648bda0d74

Rebooting...
E (110) esp_core_dump_flash: Core dump data check failed:
Calculated checksum='0403c070'
Image chec
SD opened successfuly
File removed!
Started
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
Stop
StGuru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0).

**Comment by Alireza99Salehi** [comment]
Hi, Jason! Thanks for reaching out. 
I'm deeply sorry but currently I'm not able to validate this problem. I'm afraid you haven't provided enough information either. But as of my last knowledge I was able to run the sample code smoothly. 
However, I will check the alleged problems as i find an occasion.

**Comment by JasonYANG170** [comment]
Thanks for the reply. The ESP32C3 I use is compiled with PlatformIO. The sample program I use is not modified in any way. I don’t know why.

**Comment by Alireza99Salehi** [comment]
The original test and trials were done in the Arduino IDE environment using ESP32 WROOM. There might be some incompatibility in Core IDF version and some other factors which must be investigated in order to diagnose the issue.

**Comment by JasonYANG170** [comment]
okay,thanks

**Comment by Alireza99Salehi** [comment]
I sincerely hope you will get it working. If so please let us know the issue so that future users might benefit. 
regards 
A.R.S.D

**Comment by JasonYANG170** [comment]
I will research and wait until I find the reason
